# Generated by Django 5.0.7 on 2024-07-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
